<?php
/**
 * @file
 * The phase2_social module.
 */

require_once 'includes/callbacks.inc';
require_once 'includes/permissions.inc';
require_once 'includes/meta.inc';
require_once 'includes/render.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function phase2_social_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && !empty($plugin_type)) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_menu().
 *
 * @todo Break out each social site into its own module.
 */
function phase2_social_menu() {
  $items['admin/config/content/phase2-social'] = array(
    'title' => t('Phase2 Social'),
    'description' => t('Configure settings for social networks.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('phase2_social_settings_form'),
    'access arguments' => array('administer phase2 social'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/admin.inc',
  );
  $items['admin/config/content/phase2-social/facebook'] = array(
    'title' => t('Phase2 Social - Facebook'),
    'page arguments' => array(4),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'includes/admin.inc',
  );
  $items['admin/config/content/phase2-social/twitter'] = array(
    'title' => t('Phase2 Social - Twitter'),
    'page arguments' => array(4),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/admin.inc',
  );
  $items['admin/config/content/phase2-social/linkedin'] = array(
    'title' => t('Phase2 Social - LinkedIn'),
    'page arguments' => array(4),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/admin.inc',
  );

  return $items;
}

/**
 * Returns information about widgets.
 *
 * @param string $network
 *   The name of a social network.
 * @param boolean $reset
 *   Clears static cache.
 *
 * @return array|mixed
 *   All social networks or a specific one.
 */
function phase2_social_widgets_info($network = NULL, $reset = FALSE) {
  // Use the advanced drupal_static() pattern.
  static $drupal_static_fast;
  if ($reset || !isset($drupal_static_fast)) {
    $drupal_static_fast['social_info'] = &drupal_static(__FUNCTION__);
  }
  $social_info = &$drupal_static_fast['social_info'];

  if (empty($social_info) || !isset($social_info)) {
    $social_info = module_invoke_all('social_info');
    foreach ($social_info as $name => $info) {
      // Check our settings to ensure the widget is enabled.
      // @todo Fix this so we aren't locked into this naming convention.
      $enabled = variable_get('p2_social_' . $name . '_enabled', FALSE);
      if ($enabled) {
        $social_info[$name] += array(
          'enabled' => $enabled,
        );
      }
    }
    drupal_alter('social_info', $social_info);
  }

  if (empty($network)) {
    return $social_info;
  }
  elseif (isset($social_info[$network])) {
    return $social_info[$network];
  }
}

/**
 * Implements hook_social_info().
 *
 * @todo Make some of this available in the settings form.
 *
 * @todo Rewrite this class based so we can ensure required elements
 * actually exist.
 */
function phase2_social_social_info() {
  return array(
    'facebook' => array(
      'title' => t('Facebook'),
      'icons' => array(
        'fa fa-square-o fa-stack-2x',
        'fa fa-facebook fa-stack-1x',
      ),
      'class' => array('fa-stack fa-lg'),
      'variables' => array(
        'url' => 'phase2_social_share_url',
      ),
      'render' => 'phase2_social_widget_render',
      'theme' => 'phase2_social_widget_facebook',
      'settings' => 'phase2_social_facebook_fieldset',
    ),
    'twitter' => array(
      'title' => t('Twitter'),
      'icons' => array(
        'fa fa-square-o fa-stack-2x',
        'fa fa-twitter fa-stack-1x',
      ),
      'class' => array('fa-stack fa-lg'),
      'variables' => array(
        'text' => 'phase2_social_twitter_share_message',
        'url' => 'phase2_social_share_url',
      ),
      'render' => 'phase2_social_widget_render',
      'theme' => 'phase2_social_widget_twitter',
      'settings' => 'phase2_social_twitter_fieldset',
    ),
    'linkedin' => array(
      'title' => t('LinkedIn'),
      'icons' => array(
        'fa fa-square-o fa-stack-2x',
        'fa fa-linkedin fa-stack-1x',
      ),
      'class' => array('fa-stack fa-lg'),
      'variables' => array(
        'url' => 'phase2_social_share_url',
        'title' => 'phase2_social_share_title',
        'summary' => 'phase2_social_twitter_share_message',
        'source' => 'phase2_social_share_url',
      ),
      'render' => 'phase2_social_widget_render',
      'theme' => 'phase2_social_widget_linkedin',
      'settings' => 'phase2_social_linkedin_fieldset',
    ),
    'pintrest' => array(
      'title' => t('Pintrest'),
      'icons' => array(
        'fa fa-square-o fa-stack-2x',
        'fa fa-pintrest fa-stack-1x',
      ),
      'class' => array('fa-stack fa-lg'),
      'variables' => array(
        'url' => 'phase2_social_share_url',
        'title' => 'phase2_social_share_title',
        'summary' => 'phase2_social_share_message',
        'source' => 'phase2_social_share_url',
      ),
      'render' => 'phase2_social_widget_render',
      'theme' => 'phase2_social_widget_pintrest',
      'settings' => 'phase2_social_pintrest_fieldset',
    ),
    'email' => array(
      'title' => t('Email'),
      'icons' => array(
        'fa fa-square-o fa-stack-2x',
        'fa fa-envelope fa-stack-1x',
      ),
      'class' => array('fa-stack fa-lg'),
      'variables' => array(
        'subject' => 'phase2_social_share_title',
        'body' => 'phase2_social_share_message',
      ),
      'render' => 'phase2_social_widget_render',
      'theme' => 'phase2_social_widget_email',
      'settings' => 'phase2_social_email_fieldset',
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function phase2_social_node_view($node, $view_mode, $langcode) {
  // Add meta tags.
  if ($view_mode == 'default') {
    phase2_social_open_graph($node);
  }
}

if (module_exists('panopoly_magic')) {
  /**
   * Implements hook_panopoly_magic_forms_to_improve_alter().
   */
  function phase2_social_panopoly_magic_forms_to_improve_alter(&$form_ids) {
    $form_ids[] = 'phase2_social_social_widget_content_type_edit_form';
  }
}
